### ISSUE TITLE
R packages not available from conda

### ISSUE THREAD

**Issue by csoneson** [csoneson/rnaseqworkflow#19]
This could be e.g. new packages or packages for which one would like a specific version which is not available via conda. How do we handle this? Maybe one option would be to have an R script with dedicated code to install all such packages, and a rule to run this script and install the packages in the environment?

**Comment by sorjuela** [comment]
For this I was thinking that it depends on:
1. If the user wants a different version of a package that IS or is NOT available on conda, and they don't want any of the versions listed in the environment we provide (user specific).
2. There is a specific package that should be included in order for the pipeline to run, but it is not on conda (not user specific).

* For the first case, the user will have to exclude the package from the environment list, and do the installation manually. We could provide an explanation in the wiki to do something like
`devtools::install_version("ggplot2", version = "0.9.1", repos = "http://cran.us.r-project.org")`, but I guess we shouldn't make an extra rule for these cases, because it's just too specific.

* For the second case, I have been using for `tximeta`:
`options(unzip = "internal")
devtools::install_github("mikelove/tximeta")`

I don't know why, but to install packages for a specific environment there's a weird bug reported here: https://github.com/r-lib/devtools/issues/1722 that is solved by using the code above.

This could be included in an extra rule, and removed once the package is available on conda.

**Comment by sorjuela** [comment]
Yes that sounds good. So maybe it would have the `tximeta` because this is currently mandatory, but it is also the example if you want to include other packages?

**Comment by csoneson** [comment]
Yes, I think this sounds reasonable.

**Comment by sorjuela** [comment]
And that would be it right? Or we also have to explain in that script something about the environment? or are those two lines of code enough? well with more explanation?

**Comment by csoneson** [comment]
I think that should be it, and then add some text in the documentation that says what it does and some examples of when you want to modify it. And I guess the main rule should depend on this rule, so that when the script is updated, the rule is executed.

**Comment by csoneson** [comment]
Not an issue anymore, since all packages are installed with BiocManager.
